---
    name: "tagged-release"

    on:
      push:
        tags:
          - "v*"

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    jobs:
      ubuntu_14:
        name: ubuntu_14
        runs-on: ubuntu-22.04
        container:
          image: ubuntu:14.04
          volumes:
            - /node20217:/node20217:rw,rshared
            - /node20217:/__e/node20:ro,rshared
        steps:
          - name: install git
            run: sudo apt-get install -y software-properties-common && sudo add-apt-repository ppa:git-core/ppa && sudo apt-get update -y && sudo apt-get install git -y
          - name: install packages
            run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc g++ autoconf automake make wget curl
          - name: nodejs
            run: |
              apt-get install -y wget xz-utils
              wget https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
              tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
          - uses: actions/checkout@v2
          - name: install htslib
            run: ./scripts/install-hts.sh
          - name: build release
            run: make release
          - uses: "marvinpinto/action-automatic-releases@latest"
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              prerelease: false
              title: "minimod-${{ github.ref_name  }}"
              files: |
                *.tar.gz